### ISSUE TITLE
Accessibility issue?

### ISSUE THREAD

**Issue by adrianna16** [adrianna16/web-design-2-independent-project#8]
Its saying there is issues with my store location and I do not understand why its telling me this. I have an alt attribute so I do not get why there is an issue. @thatkidmadrid

**Comment by thatkidmadrid** [comment]
can you please send a screenshot of the error

**Comment by thatkidmadrid** [comment]
So this is the same situation as the header image I said should be iunside of a wrapper with a role . An easy fix would be to move the section into your main

You had it as an aside before - that should be fine because asides have intrinsic roles
but you can make it even better by giving the aside a role of complementary

`<aside role="complementary">`

After fixing that the only other blockers I see are related to colour contrast
https://webaim.org/resources/contrastchecker/
